/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalhoordemservico;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ferna
 */
public class FrameServicosPecas extends javax.swing.JFrame {
    
    private DefaultTableModel modeloServico = new DefaultTableModel();
    private DefaultTableModel modeloPecas = new DefaultTableModel();

    private int linhaSelecionadaServicos = -1;
    private int linhaSelecionadaPecas = -1;
    
    private Double custoServicos = 0.0;
    private Double custoPecas = 0.0;
    private Double custoTotal = 0.0;
    
    private Double custoServicoEditado = 0.0;
    private Double custoPecaEditado = 0.0;

    /**
     * Creates new form FrameServicosPecas
     */
    public FrameServicosPecas() {
        initComponents();
        setLocationRelativeTo(this);
        carregaTabelaServicos();
        carregaTabelaPecas();
    }
    
    public void carregaTabelaServicos() {
        modeloServico.addColumn("Descrição");
        modeloServico.addColumn("Custo");
        tbServicos.setModel(modeloServico);
        tbServicos.getColumnModel().getColumn(0).setPreferredWidth(300);
        tbServicos.getColumnModel().getColumn(1).setPreferredWidth(10);
    }
        
    public void carregaTabelaPecas() {
        modeloPecas.addColumn("Nome");
        modeloPecas.addColumn("Quantidade");
        modeloPecas.addColumn("Preço Unitário");
        tbPecas.setModel(modeloPecas);
        tbPecas.getColumnModel().getColumn(0).setPreferredWidth(200);
        tbPecas.getColumnModel().getColumn(1).setPreferredWidth(20);
        tbPecas.getColumnModel().getColumn(2).setPreferredWidth(20);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tableServicos = new javax.swing.JScrollPane();
        tbServicos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfDescricaoServico = new javax.swing.JTextField();
        tfCustoServico = new javax.swing.JTextField();
        btAdicionarServico = new javax.swing.JButton();
        btEditarServico = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbPrecoTotalServicos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tablePecas = new javax.swing.JScrollPane();
        tbPecas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tfNomePeca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfQuantidadePeca = new javax.swing.JTextField();
        tfPrecoUnitarioPeca = new javax.swing.JTextField();
        btAdicionarPeca = new javax.swing.JButton();
        btEditarPeca = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbTotalPecas = new javax.swing.JLabel();
        btProximo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Serviços"));

        tbServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableServicos.setViewportView(tbServicos);

        jLabel1.setText("Descrição");

        jLabel2.setText("Custo");

        tfCustoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCustoServicoActionPerformed(evt);
            }
        });

        btAdicionarServico.setText("Adicionar");
        btAdicionarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarServicoActionPerformed(evt);
            }
        });

        btEditarServico.setText("Editar");
        btEditarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarServicoActionPerformed(evt);
            }
        });

        jLabel6.setText("Total Serviços:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tableServicos, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfDescricaoServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCustoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAdicionarServico)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPrecoTotalServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEditarServico)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDescricaoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCustoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdicionarServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPrecoTotalServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btEditarServico)
                        .addComponent(jLabel6)))
                .addGap(9, 9, 9))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Peças"));

        tbPecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePecas.setViewportView(tbPecas);

        jLabel3.setText("Nome");

        jLabel4.setText("Quantidade");

        jLabel5.setText("Preço Unitário");

        tfQuantidadePeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadePecaActionPerformed(evt);
            }
        });

        btAdicionarPeca.setText("Adicionar");
        btAdicionarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarPecaActionPerformed(evt);
            }
        });

        btEditarPeca.setText("Editar");
        btEditarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarPecaActionPerformed(evt);
            }
        });

        jLabel7.setText("Total Peças:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablePecas, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 255, Short.MAX_VALUE))
                            .addComponent(tfNomePeca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfQuantidadePeca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfPrecoUnitarioPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAdicionarPeca))
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEditarPeca)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfQuantidadePeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrecoUnitarioPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdicionarPeca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablePecas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btEditarPeca)
                        .addComponent(jLabel7))
                    .addComponent(lbTotalPecas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btProximo.setText("Próximo");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Serviços e Peças:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btProximo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btProximo)
                        .addComponent(jLabel8)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarServicoActionPerformed
        String descricao = tfDescricaoServico.getText();
        Double custo = Double.parseDouble(tfCustoServico.getText());
        
        if (!descricao.isEmpty() && !tfCustoServico.getText().isEmpty()) {
            if (linhaSelecionadaServicos >= 0) {
                modeloServico.removeRow(linhaSelecionadaServicos);
                modeloServico.insertRow(linhaSelecionadaServicos, new Object[]{descricao, custo.toString()});
                custoServicos -= custoServicoEditado;
                custoTotal -= custoServicoEditado;
                JOptionPane.showMessageDialog(this, "Serviço editado com sucesso!");
            } else {
                modeloServico.addRow(new Object[]{descricao, custo.toString()});
                JOptionPane.showMessageDialog(this, "Serviço adicionado com sucesso!");
            }

            try {
                custoServicos += custo;
                custoTotal += custo;
                lbPrecoTotalServicos.setText(custoServicos.toString());
                lbTotal.setText(custoTotal.toString());
            } catch(Exception ex) {
                JOptionPane.showMessageDialog(this, "Informe um custo válido!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
            tfDescricaoServico.setText("");
            tfCustoServico.setText("");
            tfDescricaoServico.requestFocus();
            linhaSelecionadaServicos = -1;
        } else {
            JOptionPane.showMessageDialog(this, "Os campos de descrição e custo devem ser preenchidos!");
        }
    }//GEN-LAST:event_btAdicionarServicoActionPerformed

    private void tfCustoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCustoServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCustoServicoActionPerformed

    private void tfQuantidadePecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadePecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadePecaActionPerformed

    private void btAdicionarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarPecaActionPerformed
        String nome = tfNomePeca.getText();
        int quantidade = Integer.parseInt(tfQuantidadePeca.getText());
        Double precoUnitario = Double.parseDouble(tfPrecoUnitarioPeca.getText());
        
        if (!nome.isEmpty() && !tfQuantidadePeca.getText().isEmpty() && !tfPrecoUnitarioPeca.getText().isEmpty()) {
            if (linhaSelecionadaPecas >= 0) {
                modeloPecas.removeRow(linhaSelecionadaPecas);
                modeloPecas.insertRow(linhaSelecionadaPecas, new Object[]{nome, String.valueOf(quantidade), precoUnitario.toString()});
                custoPecas -= custoPecaEditado;
                custoTotal -= custoPecaEditado;
                JOptionPane.showMessageDialog(this, "Peça editada com sucesso!");
            } else {
                modeloPecas.addRow(new Object[]{nome, String.valueOf(quantidade), precoUnitario.toString()});
                JOptionPane.showMessageDialog(this, "Peça adicionada com sucesso!");
            }

            try {
                Double preco = precoUnitario * quantidade;
                custoPecas += preco;
                custoTotal += preco;
                lbTotalPecas.setText(custoPecas.toString());
                lbTotal.setText(custoTotal.toString());
            } catch(Exception ex) {
                JOptionPane.showMessageDialog(this, "Informe um preço válido!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
            tfNomePeca.setText("");
            tfQuantidadePeca.setText("");
            tfPrecoUnitarioPeca.setText("");
            tfNomePeca.requestFocus();
            linhaSelecionadaPecas = -1;
        } else {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!");
        }
    }//GEN-LAST:event_btAdicionarPecaActionPerformed

    private void btEditarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarServicoActionPerformed
        linhaSelecionadaServicos = -1;
        linhaSelecionadaServicos = tbServicos.getSelectedRow();
        
        if(linhaSelecionadaServicos >= 0) {
            String descricao = (String)tbServicos.getValueAt(linhaSelecionadaServicos, 0);
            String custo = (String)tbServicos.getValueAt(linhaSelecionadaServicos, 1);
            
            custoServicoEditado = Double.parseDouble(custo);
            
            tfDescricaoServico.setText(descricao);
            tfCustoServico.setText(custo);
        } else {
                JOptionPane.showMessageDialog(this, "Selecione um registro na tabela!");           
        }
    }//GEN-LAST:event_btEditarServicoActionPerformed

    private void btEditarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarPecaActionPerformed
        linhaSelecionadaPecas = -1;
        linhaSelecionadaPecas = tbPecas.getSelectedRow();
        
        if(linhaSelecionadaPecas >= 0) {
            String nome = (String)tbPecas.getValueAt(linhaSelecionadaPecas, 0);
            String quantidade = (String)tbPecas.getValueAt(linhaSelecionadaPecas, 1);
            String preco = (String)tbPecas.getValueAt(linhaSelecionadaPecas, 2);
            
            custoPecaEditado = Double.parseDouble(preco) * Integer.parseInt(quantidade);

            tfNomePeca.setText(nome);
            tfQuantidadePeca.setText(quantidade);
            tfPrecoUnitarioPeca.setText(preco);
        } else {
                JOptionPane.showMessageDialog(this, "Selecione um registro na tabela!");           
        }
    }//GEN-LAST:event_btEditarPecaActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        FrameResumo resumo = new FrameResumo(modeloServico, modeloPecas, custoServicos, custoPecas, custoTotal);
        resumo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btProximoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarPeca;
    private javax.swing.JButton btAdicionarServico;
    private javax.swing.JButton btEditarPeca;
    private javax.swing.JButton btEditarServico;
    private javax.swing.JButton btProximo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbPrecoTotalServicos;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotalPecas;
    private javax.swing.JScrollPane tablePecas;
    private javax.swing.JScrollPane tableServicos;
    private javax.swing.JTable tbPecas;
    private javax.swing.JTable tbServicos;
    private javax.swing.JTextField tfCustoServico;
    private javax.swing.JTextField tfDescricaoServico;
    private javax.swing.JTextField tfNomePeca;
    private javax.swing.JTextField tfPrecoUnitarioPeca;
    private javax.swing.JTextField tfQuantidadePeca;
    // End of variables declaration//GEN-END:variables
}
